# Generated by Django 5.2.7 on 2025-11-06 22:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblFactorDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField(unique=True)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TBL_FACTOR_DEF',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='TblInstrumento',
            fields=[
                ('instrumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Instrumento')),
                ('tipo_instrumento', models.CharField(max_length=20, verbose_name='Tipo de Instrumento')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'TBL_INSTRUMENTO',
            },
        ),
        migrations.CreateModel(
            name='TblMercado',
            fields=[
                ('mercado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre del Mercado')),
                ('codigo', models.CharField(blank=True, max_length=10, verbose_name='Código (opcional)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'db_table': 'TBL_MERCADO',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TblTipoIngreso',
            fields=[
                ('tipo_ingreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_ingreso', models.CharField(max_length=50, verbose_name='Nombre del Tipo de Ingreso')),
                ('prioridad', models.IntegerField(help_text='Regla de prevalencia (p.ej. Corredor > Bolsa)', verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Tipo de Ingreso',
                'verbose_name_plural': 'Tipos de Ingreso',
                'db_table': 'TBL_TIPO_INGRESO',
                'ordering': ['prioridad'],
            },
        ),
        migrations.CreateModel(
            name='TblArchivoFuente',
            fields=[
                ('archivo_fuente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_almacenamiento', models.CharField(max_length=255, verbose_name='Ruta de Almacenamiento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que subió el archivo')),
            ],
            options={
                'verbose_name': 'Archivo Fuente',
                'verbose_name_plural': 'Archivos Fuente',
                'db_table': 'TBL_ARCHIVO_FUENTE',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TblCalificacion',
            fields=[
                ('calificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('instrumento_text', models.CharField(max_length=120, verbose_name='Instrumento')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('fecha_pago_dividendo', models.DateField(verbose_name='Fecha Pago')),
                ('ejercicio', models.IntegerField(verbose_name='Año')),
                ('secuencia_evento', models.IntegerField(help_text='Debe ser mayor a 10000', validators=[django.core.validators.MinValueValidator(10001)], verbose_name='Secuencia Evento')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('dividendo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_historico', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('isfut', models.BooleanField(default=False, verbose_name='ISFUT')),
                ('factor_actualizacion', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('archivo_fuente', models.ForeignKey(blank=True, db_column='archivo_fuente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='core.tblarchivofuente', verbose_name='Archivo Fuente')),
                ('usuario', models.ForeignKey(db_column='usuario_modificacion_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
                ('instrumento', models.ForeignKey(blank=True, db_column='instrumento_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tblinstrumento', verbose_name='Instrumento (catálogo, opcional)')),
                ('mercado', models.ForeignKey(db_column='mercado_id', on_delete=django.db.models.deletion.PROTECT, to='core.tblmercado', verbose_name='Mercado')),
                ('tipo_ingreso', models.ForeignKey(db_column='tipo_ingreso_id', on_delete=django.db.models.deletion.PROTECT, to='core.tbltipoingreso', verbose_name='Tipo de Ingreso')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'db_table': 'TBL_CALIFICACION',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TblFactorValor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.PositiveSmallIntegerField(verbose_name='Posición (8..37)')),
                ('monto_base', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Monto Base')),
                ('valor', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Factor Calculado (0..1)')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='core.tblcalificacion', verbose_name='Calificación')),
                ('factor_def', models.ForeignKey(blank=True, db_column='factor_def_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='core.tblfactordef')),
            ],
            options={
                'db_table': 'TBL_FACTOR_VALOR',
                'indexes': [models.Index(fields=['calificacion', 'posicion'], name='TBL_FACTOR__calific_34538d_idx')],
                'unique_together': {('calificacion', 'posicion')},
            },
        ),
        migrations.AddIndex(
            model_name='tblcalificacion',
            index=models.Index(fields=['ejercicio', 'mercado'], name='TBL_CALIFIC_ejercic_9fa35b_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcalificacion',
            index=models.Index(fields=['secuencia_evento'], name='TBL_CALIFIC_secuenc_6b0c58_idx'),
        ),
    ]
