# Generated by Django 5.2.7 on 2025-10-31 03:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblInstrumento',
            fields=[
                ('instrumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Instrumento')),
                ('tipo_instrumento', models.CharField(max_length=20, verbose_name='Tipo de Instrumento')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'TBL_INSTRUMENTO',
            },
        ),
        migrations.CreateModel(
            name='TblTipoIngreso',
            fields=[
                ('tipo_ingreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_ingreso', models.CharField(max_length=50, verbose_name='Nombre del Tipo de Ingreso')),
                ('prioridad', models.IntegerField(help_text=' Regla de prevalencia: Corredor > Bolsa', verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Tipo de Ingreso',
                'verbose_name_plural': 'Tipos de Ingreso',
                'db_table': 'TBL_TIPO_INGRESO',
                'ordering': ['prioridad'],
            },
        ),
        migrations.CreateModel(
            name='TblArchivoFuente',
            fields=[
                ('archivo_fuente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_almacenamiento', models.CharField(max_length=255, verbose_name='Ruta de Almacenamiento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que subió el archivo')),
            ],
            options={
                'verbose_name': 'Archivo Fuente',
                'verbose_name_plural': 'Archivos Fuente',
                'db_table': 'TBL_ARCHIVO_FUENTE',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TblCalificacion',
            fields=[
                ('calificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('ejercicio', models.IntegerField(verbose_name='Ejercicio (Año)')),
                ('mercado', models.CharField(max_length=60, verbose_name='Mercado')),
                ('secuencia_evento', models.IntegerField(help_text='Debe ser mayor 10001', validators=[django.core.validators.MinValueValidator(10001)])),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modifición', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('fecha_pago_dividendo', models.DateField(verbose_name='Fecha Pago Dividendo')),
                ('dividendo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Dividendo')),
                ('valor_historico', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Histórico')),
                ('isfut', models.BooleanField(default=False, verbose_name='ISFUT')),
                ('factor_actualizacion', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Factor Actualización')),
                ('archivo_fuente', models.ForeignKey(blank=True, db_column='usuario_fuente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='core.tblarchivofuente', verbose_name='Archivo Fuente')),
                ('usuario', models.ForeignKey(db_column='usuario_modificacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
                ('instrumento', models.ForeignKey(db_column='instrumento_id', on_delete=django.db.models.deletion.PROTECT, to='core.tblinstrumento', verbose_name='Instrumento')),
                ('tipo_ingreso', models.ForeignKey(db_column='tipo_ingreso_id ', on_delete=django.db.models.deletion.PROTECT, to='core.tbltipoingreso', verbose_name='Tipo de Ingreso')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'db_table': 'TBL_CALIFICACION',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['ejercicio', 'mercado'], name='TBL_CALIFIC_ejercic_4141b7_idx'), models.Index(fields=['secuencia_evento'], name='TBL_CALIFIC_secuenc_6b0c58_idx')],
            },
        ),
    ]
