# Generated by Django 5.2.7 on 2025-10-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tblinstrumento_tbltipoingreso_tblarchivofuente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcalificacion',
            old_name='fecha_modifición',
            new_name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='archivo_fuente',
            field=models.ForeignKey(blank=True, db_column='archivo_fuente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='core.tblarchivofuente', verbose_name='Archivo Fuente'),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='tipo_ingreso',
            field=models.ForeignKey(db_column='tipo_ingreso_id', on_delete=django.db.models.deletion.PROTECT, to='core.tbltipoingreso', verbose_name='Tipo de Ingreso'),
        ),
        migrations.CreateModel(
            name='TblFactorValor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(decimal_places=8, max_digits=9)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='core.tblcalificacion')),
            ],
            options={
                'db_table': 'TBL_FACTOR_VALOR',
                'indexes': [models.Index(fields=['calificacion', 'posicion'], name='TBL_FACTOR__calific_34538d_idx')],
                'unique_together': {('calificacion', 'posicion')},
            },
        ),
    ]
