# Generated by Django 5.2.7 on 2025-11-02 17:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_fecha_modifición_tblcalificacion_fecha_modificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleUser',
        ),
        migrations.AddField(
            model_name='tblcalificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tblcalificacion',
            name='instrumento_text',
            field=models.CharField(default='PENDIENTE', max_length=120, verbose_name='Instrumento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblfactorvalor',
            name='monto_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Monto Base'),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='dividendo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='ejercicio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='factor_actualizacion',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='fecha_pago_dividendo',
            field=models.DateField(verbose_name='Fecha Pago'),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='instrumento',
            field=models.ForeignKey(blank=True, db_column='instrumento_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tblinstrumento', verbose_name='Instrumento (catálogo, opcional)'),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='secuencia_evento',
            field=models.IntegerField(help_text='Debe ser mayor a 10000', validators=[django.core.validators.MinValueValidator(10001)], verbose_name='Secuencia Evento'),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_modificacion_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='valor_historico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tblfactorvalor',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='core.tblcalificacion', verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='tblfactorvalor',
            name='posicion',
            field=models.PositiveSmallIntegerField(verbose_name='Posición (8..37)'),
        ),
        migrations.AlterField(
            model_name='tblfactorvalor',
            name='valor',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Factor Calculado (0..1)'),
        ),
        migrations.AlterField(
            model_name='tbltipoingreso',
            name='prioridad',
            field=models.IntegerField(help_text='Regla de prevalencia (p.ej. Corredor > Bolsa)', verbose_name='Prioridad'),
        ),
    ]
