# Generated by Django 5.2.7 on 2025-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEventDB',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField()),
                ('table_schema', models.CharField(max_length=64)),
                ('table_name', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=1)),
                ('row_pk', models.CharField(max_length=128)),
                ('db_user', models.CharField(max_length=128)),
                ('app_name', models.CharField(blank=True, max_length=256, null=True)),
                ('app_user', models.CharField(blank=True, max_length=128, null=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('before_row', models.JSONField(blank=True, null=True)),
                ('after_row', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit"."events',
                'ordering': ['-changed_at'],
                'managed': False,
            },
        ),
    ]
