# Generated by Django 5.2.7 on 2025-11-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditeventdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditeventdb',
            options={'managed': False, 'ordering': ['-changed_at'], 'verbose_name': 'Evento de Auditoría', 'verbose_name_plural': 'Eventos de Auditoría'},
        ),
    ]
