# Generated by Django 5.2.7 on 2025-11-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_simpleuser_tblcalificacion_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblFactorDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField(unique=True)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TBL_FACTOR_DEF',
                'ordering': ['posicion'],
            },
        ),
        migrations.AddField(
            model_name='tblfactorvalor',
            name='factor_def',
            field=models.ForeignKey(blank=True, db_column='factor_def_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='core.tblfactordef'),
        ),
    ]
