# Generated by Django 5.2.7 on 2025-12-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditeventdb_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblarchivofuente',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='calificaciones/%Y/%m/%d', verbose_name='Archivo subido (S3 / almacenamiento de archivos)'),
        ),
        migrations.AlterField(
            model_name='tblarchivofuente',
            name='ruta_almacenamiento',
            field=models.CharField(blank=True, help_text='Opcional; se puede dejar vacío cuando se usa S3.', max_length=255, verbose_name='Ruta de Almacenamiento (legacy)'),
        ),
    ]
