# Generated by Django 5.2.7 on 2025-11-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_factor_def'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMercado',
            fields=[
                ('mercado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre del Mercado')),
                ('codigo', models.CharField(blank=True, max_length=10, verbose_name='Código (opcional)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'db_table': 'TBL_MERCADO',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameIndex(
            model_name='tblcalificacion',
            new_name='TBL_CALIFIC_ejercic_9fa35b_idx',
            old_name='TBL_CALIFIC_ejercic_4141b7_idx',
        ),
        migrations.AlterField(
            model_name='tblcalificacion',
            name='mercado',
            field=models.ForeignKey(db_column='mercado_id', on_delete=django.db.models.deletion.PROTECT, to='core.tblmercado', verbose_name='Mercado'),
        ),
    ]
