# Generated by Django 5.2.7 on 2025-12-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tblarchivofuente_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblarchivofuente',
            name='hash_contenido',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash del contenido del archivo', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tblarchivofuente',
            name='tamanio_bytes',
            field=models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True),
        ),
    ]
